apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "cluster-vtg-spec-teste"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: production
    grafana_obs_api: https://grafana.ambima-cluster-demo.vkpr.platform.vee.codes
    public_ip: 44.216.85.174
  annotations:
    backstage.io/kubernetes-id: "cluster-vtg-spec-teste"
    github.com/project-slug: veecode-homolog/cluster-vtg-spec-teste
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$44.216.85.174 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$44.216.85.174:~/.kube/config ~/.kube/config-cluster-vtg-spec-teste\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"44.216.85.174\")' -i ~/.kube/config-cluster-vtg-spec-teste\n  export KUBECONFIG=~/.kube/config-cluster-vtg-spec-teste\n  kubectl get pods -A\n"
    veecode/cluster-name: cluster-vtg-spec-teste
    kubernetes.io/secret-name: cluster-vtg-spec-teste-secret
    kubernetes.io/secret-namespace: veecode-homolog
    kubernetes.io/auth-provider: custom
    kubernetes.io/api-server: https://44.216.85.174:6550
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
